### ISSUE TITLE
Model bootstrapping

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#1]

**Comment by eichelbe** [comment]
Currently bootstrapping the source code with a model needs to be done manually (see documentation). Some form of support mechanism in the tool would be appreciated.

**Comment by eichelbe** [comment]
See #5 ;)

**Comment by sassai** [comment]
Should the model be downloaded automatically from #5 ?

**Comment by eichelbe** [comment]
Could be an option. Initially, we planned just to commit a stable version into GitHub.

**Comment by eichelbe** [comment]
Initial model is available on Jenkins. Fixed some NPEs due to an empty model. 
Need to clarify with Aike what the initial model shall contain in addition, e.g., the EASy folder, .project, .classpath or pom.xml.

**Comment by sassai** [comment]
Initial bootstrapping dialog has been committed. Please test and see if this fits the requirements.

**Comment by eichelbe** [comment]
Looks nice :) Would be nice to enter the SVN URL with a default to the QM one...

**Comment by sassai** [comment]
Done
