### ISSUE TITLE
Handling users, passwords, tokens, etc.

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#100]
Decide for an approach how to handle passwords in the infrastructure and change the configuration model accordingly. Currently we have them in (potentially not reusable) code, the configuration, elsewhere. At least from the configuration point of view (see email) it makes sense just to have the user name (or some user identification) in the configuration while accessing the actual tokens/passwords through an infrastructure service. However, this requires that the tokens/passwords are stored/installed manually on the cluster (distributed fashion) or updated regularly from a safe side, e.g., the L3S SVN.

**Comment by eichelbe** [comment]
see https://github.com/QualiMaster/Infrastructure/issues/5

**Comment by eichelbe** [comment]
see #51

**Comment by eichelbe** [comment]
Infrastructure is decided and realized. We just need parameters for (virtual) user names with default values, Strings or comma-separated Strings for sinks. Needs to be done step-by step with each partner.

**Comment by eichelbe** [comment]
WP 5 needs to collect state...

**Comment by eichelbe** [comment]
-	TSI algorithms are done
-	External service must be done
-	LUH unclear

**Comment by ap0n** [comment]
My bad. The passwords handling is ready on the external service as well.
Log in functionality is still pending

**Comment by eichelbe** [comment]
Fine. Shall we go on with user name parameter (comma-separated list) so that we can configure it or do you already have it?

**Comment by ap0n** [comment]
I'm not sure I get what you mean.

I currently use an `accounts.properties` file to get the usernames and passwords and it's working nicely. I also used it for the login functionality -- also works.

**Comment by eichelbe** [comment]
Right, better than fixed. We can stay with that, but so the external service cannot be configured consistently for an individual pipeline...

**Comment by ap0n** [comment]
Still don't get it. Are we going to have different users per pipeline? I thought that users are not pipeline-dependent...

**Comment by eichelbe** [comment]
In principle, that's possible - to provide different services (also of different quality) to different users. I don't insist on that, but it might make sense to ask Stefan whether this could be a business case...

**Comment by ap0n** [comment]
Ok, I see now. However, maybe it's better to base the different level of services on the user roles -- not the users. Anyway, Stefan should decide on that...

**Comment by eichelbe** [comment]
Roles are also fine for me... could be attached to users or so. Who shall ask Stefan? Unfortunately, we do not have him in github :o

**Comment by eichelbe** [comment]
After asking Stefan, we stay with the user roles within the account file as Apostolos suggested and shall be done with that (except for changes to the protocol if needed).
