### ISSUE TITLE
Check whether the reasoner works without forced initialization

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#101]
Currently, a set of user-defined operations on pipelines force a kind of initialization. However, the reasoner shall return the correct value without that as it shall return the correct values independent of the evaluation sequence. Thus, please simplify the user-defined operations on the pipelines as they were before and check whether the reasoner passes all defined QM-IConf tests (see document).

**Comment by eichelbe** [comment]
Any news here?

**Comment by eichelbe** [comment]
...

**Comment by eichelbe** [comment]
does it work (also after the last loading modifications by Sascha)?

**Comment by eichelbe** [comment]
Seems to be working: Open:
- compare reasoner execution time (Roman)
- crosscheck and commit (Sascha, Cui)

**Comment by rsizonenko** [comment]
Comparison done

**Comment by eichelbe** [comment]
Results? ;)

**Comment by rsizonenko** [comment]
Sent an e-mail with results to @eichelbe @Elscha @cuiqin

**Comment by eichelbe** [comment]
Ahh.. see. My email client scrolled it down.

**Comment by eichelbe** [comment]
Was the change committed?

**Comment by rsizonenko** [comment]
Sent modified Pipelines.ivml file to @cuiqin for confirmation. Do not know if the changes were committed.

**Comment by cuiqin** [comment]
The Pipelines.ivml changes on the constraint causes problem at my machine. So they are not committed. Roman will check it.

**Comment by rsizonenko** [comment]
Fixed the problem and committed changes to Pipeline.ivml
