### ISSUE TITLE
Permissible external parameters 

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#103]
As discussed, we need to declare the permissible external parameters. We decided to link them from pipeline level, i.e., in data source, data sink and family as references to the parameters defined by the underlying element. This involves
- changing the parameters from sets to sequences (**done**)
- adding a constraint to avoid repeated parameters (**done**)
- changing the QM-IConf user interface 
- adjusting rt-VIL, considering non-permissible parameters to be rejected (**done**)

**Comment by eichelbe** [comment]
Chaning parameters / constraint in IVML is done.

**Comment by eichelbe** [comment]
How about the state here? Parameters are in and considered in the settings.xml? What about the UI?

**Comment by cuiqin** [comment]
From my side, permissible parameters are already considered in the settings xml file.

**Comment by eichelbe** [comment]
Ok, are all required permissible parameters configured? Then I can change the rt-VIL specification - otherwise, I would lock out the applications :o

**Comment by cuiqin** [comment]
What are the required permissible parameters? So far I did not get such configuration.

**Comment by eichelbe** [comment]
Please ask TSI/SPRING about the past scenarios... and their future plans ;)

**Comment by eichelbe** [comment]
ok... activated in rt-VIL - what about the UI?

**Comment by eichelbe** [comment]
Got List from Stefan... Cui will configure them.

**Comment by eichelbe** [comment]
Then we can close this issue...

**Comment by eichelbe** [comment]
... if the UI is supporting the parameters ;)
