### ISSUE TITLE
Support data replay

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#104]
From the configuration side, we need a specific ReplaySink 
- add to configuration (**done**)
- add to rt-VIL (in progress, needs testing)
- add to pipeline editor (Sascha, **done**)
- generate sink (-> Cui **done**)

**Comment by Elscha** [comment]
Re-generated pipeline editor to support _ReplaySink_s

Changes are:
- c8da532ed6d60877bc0bab920df560277269303e
- 991d92085d042fd2511c25b6935e8177e9237122

**Comment by eichelbe** [comment]
updated state...

**Comment by cuiqin** [comment]
Generation of the replay sink is done. State is updated...

**Comment by eichelbe** [comment]
Do we have a test pipeline so that we can at least do the adaptation level tests. Full cluster tests depend on Tuan's implementation.

**Comment by eichelbe** [comment]
-	Change of interfaces done
-	Test Pipeline today (@Cui)
-	Testing needed!

**Comment by cuiqin** [comment]
The configuration of the test pipeline for replay sink is done.

**Comment by eichelbe** [comment]
Cui extended SwitchPip for testing...
