### ISSUE TITLE
Support application creation

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#105]
Generate static transfer XML file for Stefan...

**Comment by eichelbe** [comment]
Initial version for Stefan send by mail and documented in Wiki

**Comment by eichelbe** [comment]
Add pipeline output fields/types and permissible parameters.
Sync with Stefan and TSI (external servers).

**Comment by eichelbe** [comment]
Changes are agreed, interfaces are changed. Delivery of files seems to work over file system. Infrastructure is updated to store the files. 
Are the setup files now part of the model artifact? What is the state of the XMLs?

**Comment by cuiqin** [comment]
yes, the setup files are packaged along with the model artifact. If I understood correctly xmls are the setup files, or? If so, they are now generated.

**Comment by eichelbe** [comment]
XMLs are setup files, correct ;)
Could you please set pipelines.settings in qm.infrastructure.cfg to a NFS folder (new empty folder for testing shall be fine, infrastructure will clean this folder) and check after restart whether the setup files are extracted correctly. Then TSI can go on here...

**Comment by eichelbe** [comment]
XMLs are deployed to Maven and can now be downloaded by the infrastructure. Test on cluster needed, also publishing them to Stefan (TSI).
