### ISSUE TITLE
Value propagation of constraint variables inside compounds does not work

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#106]
Compounds of the QM model uses if-then-else constraints for validation and propagation. However, nested constraint variables (maybe also normal constraints) of compounds are not used for value propagation.
For instance:
```
project ignoredConstraint {

  version v0;

  compound CP1 {
    Integer no;
    if isDefined(no) then no > 0 else no = 5 endif;
  }
  
  CP1 cmp;
}
```
will be ignored inside the QM-Iconf application. [EASy-Producer](https://github.com/SSEHUB/EASyProducer) will use this correctly for value propagation. The reason for this can be found in [Reasoning:69](https://github.com/QualiMaster/QM-IConf/blob/0b783ee88ecb16bb52c7b14c3b58761f731e7253/QualiMasterApplication/src/de/uni_hildesheim/sse/qmApp/model/Reasoning.java#L69) and [Reasoning:156](https://github.com/QualiMaster/QM-IConf/blob/0b783ee88ecb16bb52c7b14c3b58761f731e7253/QualiMasterApplication/src/de/uni_hildesheim/sse/qmApp/model/Reasoning.java#L156). Both lines prevent the reasoner for propagating values back to the model where they are needed for instantiation.

CC: @eichelbe, @cuiqin, @rsizonenko

**Comment by rsizonenko** [comment]
Now both QM-IConf and EASy-Producer call the reasoner in the same way - using passed configuration and propagating values to it (changed in  [Reasoning:69](https://github.com/QualiMaster/QM-IConf/blob/0b783ee88ecb16bb52c7b14c3b58761f731e7253/QualiMasterApplication/src/de/uni_hildesheim/sse/qmApp/model/Reasoning.java#L69))
If needed we can make a distinction between validation and propagation in a way that validation used fresh configuration and propagation - original configuration.
