### ISSUE TITLE
RuntimeView (Error): Obserables are displayed mutliple times

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#110]
![multipleobservables](https://cloud.githubusercontent.com/assets/6489033/16552366/cda1108c-41c0-11e6-995e-5ce0b963623a.png)

**Comment by Elscha** [comment]
It seems that this happens when the RuntimeView is closed and oppened again.

**Comment by Elscha** [comment]
Potentialy the problem relies here: [RuntimeEditor.java:791](https://github.com/QualiMaster/QM-IConf/blob/97064cd65719f7057db3015004a3ccff63525a52/QualiMasterApplication/src/de/uni_hildesheim/sse/qmApp/editors/RuntimeEditor.java#L791)
Usage of a singlenton without cleaning it is problematic. Either 

- the singleton should be removed (probably best solution)
- the singleton should be checked whether it is already initalized
- or the singleton should be cleaned up after closing the runtime view

BTW:

- I
 think that the usage of the Configuration should be more accurate than trying to parse the configuration out of the Project.
- The files and folder structure should not be hard coded into an editor (or their logical part): [PipelinesRuntimeUtils:50](https://github.com/QualiMaster/QM-IConf/blob/97064cd65719f7057db3015004a3ccff63525a52/QualiMasterApplication/src/de/uni_hildesheim/sse/qmApp/pipelineUtils/PipelinesRuntimeUtils.java#L50) - [PipelinesRuntimeUtils:54](https://github.com/QualiMaster/QM-IConf/blob/97064cd65719f7057db3015004a3ccff63525a52/QualiMasterApplication/src/de/uni_hildesheim/sse/qmApp/pipelineUtils/PipelinesRuntimeUtils.java#L54)

**Comment by eichelbe** [comment]
As the full configuration is available, the IVML object model shall be used rather than parsing it again. Further, functions from ModelQuery shall be used rather than simple getters which may fail due to imports.

**Comment by Nowatzki** [comment]
Done.
