### ISSUE TITLE
RuntimeView (Enhancement): Simplify color selection

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#112]
If I select two obserables, there is only one color selection. For which does it belong to?
![selection](https://cloud.githubusercontent.com/assets/6489033/16552526/0baff004-41c2-11e6-8437-39cc3bf2ea5d.png)Is it not possible to movbe the color selection into the list of chosen elements?

**Comment by Nowatzki** [comment]
Color can now be selected for each an every pipeline-element. Thus the ui got clearer and easier to use. -> Done.

**Comment by Elscha** [comment]
Still, only one graph is shown, but the drawable canvas area is smaller than before :unamused: 
![error](https://cloud.githubusercontent.com/assets/6489033/16769823/8f43431a-484a-11e6-966e-fc1e47547e7c.png)

**Comment by Elscha** [comment]
Sorry, was wrong issue -> closed again
