### ISSUE TITLE
RuntimeView (Enhancement): Drawing constant values

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#114]
If values do not change (for instance see **TASKS**), the drawn line is hardly to see as it is drawn at the border of the diagram.
![selection](https://cloud.githubusercontent.com/assets/6489033/16552674/3ae01c0e-41c3-11e6-8d2f-4d0f22ff9ba3.png)

**Comment by Nowatzki** [comment]
Done due to the last commit which introduced multiple y-achses for observables.
