### ISSUE TITLE
RuntimeView (Enhancement): Filter observables without values

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#116]
Some obserables are not monitored. If I select them, I get an diagram with a time range of 1:00 (1970) - 1:01 (1970). Maybe it is possible to filter such elements, which exist but do not deliver any values.
![selection](https://cloud.githubusercontent.com/assets/6489033/16552840/84c5f536-41c4-11e6-81b0-8168e3f35071.png)

**Comment by Nowatzki** [comment]
Observables get filtered. I added a tooltip which shows the observables which should be shown but do not provide data. Unfortunately there is no way in swt to disable a tree- or tableitem. Moreover I use the handleMonitoringData in RuntimeEditor for observables evaluation. This may be moved into a separate method or class... Done for now.
