### ISSUE TITLE
June release

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#118]
Fixing the sub-topology issues
Any news about the overdue release?

**Comment by rsizonenko** [comment]
Revisited failed scenarios, we still have 2 serious issues. Modified test protocol committed.

**Comment by eichelbe** [comment]
To clarify... "Browse" for artifact works. "Browse" for class loads all dependencies but does not open the class selector? If yes (happens on my side), then it's an urgent task for Patrick.
Please file the constraint editor as issue - unclear why the model does not detect the errors.

**Comment by Elscha** [comment]
I fixed three of the four issues including the constraint editor.
Patrik is ill this week. However, I'm not sure whether the bug with the artifact editor was solved in the meanwhile. Roman, did you checked that?

**Comment by eichelbe** [comment]
Thanks for fixing ;)

**Comment by rsizonenko** [comment]
Scenario 19 (Defining/changing constraints) still fails when trying from Algorithm, Source, Sink. It works when constraints are added in Pipeline editor properties.

Scenario 11 (Configuring a new Algorithm, Source or Sink via Manifests)
Source: returns error- eu/qualimaster/observables/Imeasurable after selecting class
Sink - works fine
Algorithm (new SoftwareAlgorithm) - eu/qualimaster/observables/Imeasurable

**Comment by cuiqin** [comment]
Deleting the configured pipeline causes problem. The scenario I tested was:
 - configure a test pipeline and save all changes
 - delete that pipeline

**Comment by rsizonenko** [comment]
Writing constraints outside of PipelineEditor works now.
Found another issue with removing constraints in PipelineEditor:
1) Press "..." to open Edit constraints window
2) add constraint in Edit constraints window
3) Click OK - constraint can be seen in Properties tab
4) Again press "..." - Edit constraints window opens but there are no constraints there. So a constraint that was added cannot be removed after Edit constraints window is closed.

**Comment by eichelbe** [comment]
Now also on the SSE webpage.

**Comment by eichelbe** [comment]
Can we close this issue?

**Comment by Elscha** [comment]
Release is done -> Yes, we should close this.
