### ISSUE TITLE
Bootstrapping (Error): Cannot Import Model

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#119]
Scenario:

- Downloaded [recent (beta) release](http://projects.sse.uni-hildesheim.de/qm/confApp/QMConfigApp-win64-0.10.5.zip)
- Started the application and downloaded the model from the offered [URL](jenkins.sse.uni-hildesheim.de/job/QM-Pipelines/lastSuccessfulBuild/artifact/QM_Model.zip) and unzipped it
- Selected Manually (I downloaded and unzipped the model)
- Selected the root folder of the unzipped model (the folder which contains the EASy folder) and could not finish boostrapping (cf. screenshot).

![bootstrapping](https://cloud.githubusercontent.com/assets/6489033/16609032/e7ebe2b4-4350-11e6-8741-52811a1abddd.png)

Maybe I did something wrong, but even in this case I should get a helpful error message.

**Comment by sassai** [comment]
Fixed with 4b973854b9ab59d7ba2a5692e5807772501ba2a6.
