### ISSUE TITLE
PipelineEditor (Error): Coloring is not reseted after disconnect

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#122]
After disconnecting the QM-IConf app from the infrastructure, the coloring of pipeline elements is kept.

This may lead to further errors, when reconnecting.

**Comment by Nowatzki** [comment]
I would say that the colors get overwritten when the editor is reopened. I do not see the potential error. But it can be quite irritating for the user. Should I reset the colors when a diagram gets closed?
