### ISSUE TITLE
Pipeline Deployment (Error): Wrong path is used for selecting the pom file

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#129]
When deplyoing a pipeline, the ManifestUtils searches at the wrong folder for the `pom.xml`. At the screenshot you can see, that the tool searches for the `pom.xml` in the workspace folder (`QM2.devel`) and not in the instantiation folder.
![error](https://cloud.githubusercontent.com/assets/6489033/17549033/d2e80910-5eee-11e6-9e96-e93244b31697.png)
Btw: Please also consider revising the dialog title.

**Comment by Pastuschek** [comment]
Has been resolved. Issue was connected to ivy which is no longer in use for deployment.
