### ISSUE TITLE
Use STRING-TIMESTAMP

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#132]
As discussed by email, the replay sinks need a timestamp and a key entry. For the correlation output this is currently not the case.
- Change pipelines to use STRING-TIMESTAMP
- Define some key entries

**Comment by antoine-tran** [comment]
The current String-Timestamp parser is in DataManagementLayer: eu.qualimaster.dataManagement.common.replay.ReplayUtils.getTimestamp(Field field, Object timeValue). Will be tested against the

**Comment by eichelbe** [comment]
Seems to work with QM2.devel. Backpatch to ConfModel will follow.... the next days.

**Comment by eichelbe** [comment]
Backpatch to ConfModel done...
