### ISSUE TITLE
Artifact browser dialog does not work in the deployed version

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#15]
LUH: Please check the browser dialog in particular for the deployed version (might be that Exceptions prevent it from working). Happens in particular when a new algorithm is being created.
SUH: Confirmed on Patrick's laptop :o

**Comment by PatrickSie** [comment]
![errorbrowse](https://cloud.githubusercontent.com/assets/11369535/11839946/34c10f46-a3f2-11e5-8d59-54bec2411c97.png)

**Comment by eichelbe** [comment]
The jsoup library is not build.properties of the RepositoryConnector!!

**Comment by eichelbe** [comment]
Added it to build.properties.
Function needs to be verified in deployed version!!

**Comment by eichelbe** [comment]
Explicit note in the test scenarios document.
