### ISSUE TITLE
Allow validation without family members

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#25]
For generating initial pipelines.
Please just comment it out. Might be we introduce startup times later.

**Comment by cuiqin** [comment]
As far as I checked the model, the family member check was actually commented out. The complaining about no algorithm configuration comes from the constraint checking the actual algorithm in the FamilyElement, i.e., Constraint actualAlgorithmCheck = family.members->exists(a | a == actual); It seems to me, it has something to do with its binding time.

**Comment by eichelbe** [comment]
Hmm, actual is a runtime variable and shall not lead to violations before runtime, right?

**Comment by cuiqin** [comment]
It shall not. But if we leave the family member empty, the reasoner then complains the above constraint I pointed, whyever.

**Comment by eichelbe** [comment]
Leaving it empty means it is not configured and the constraint shall not fail. Does actual have a default value in your case?

**Comment by cuiqin** [comment]
No, the actual algorithm is not configured.

**Comment by eichelbe** [comment]
Override in this case temporarily the frozen constraint variable, just in this case as an option?

**Comment by cuiqin** [comment]
turned to a mandatory constraint use the fake algorithm
