### ISSUE TITLE
Highlight validation errors

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#3]
Upon validation, highlight the validation errors in a graphical way in
- the configuration tree
- the configuration editors
- the pipeline editor

Display also the error messages in tool-tips.Consider removing / updating the highlighting upon re-validation.

**Comment by eichelbe** [comment]
Updating editors may require #2

**Comment by eichelbe** [comment]
If realized, please assign to HE for updating the test scenarios accordingly.

**Comment by Nowatzki** [comment]
Configuration Tree - Done

Configuration Editors - The controldecorations(red errors) do not diasappear after validating a currently opened editor. If the editor is reopened, the marking of flawed controls is adjusted accornigly.
Therefore we need an Update-Mechanism for editors which will be called after a run of the Reaosning. -> #2

PipelineEditor - Runs with fully integrated Error-Validation.

**Comment by eichelbe** [comment]
Caused problem in Hardware configuration for testing, but no marker occurred...

**Comment by eichelbe** [comment]
Caused problem in Pipeline configuration for testing, no marker occurred but exceptions regarding Widget is disposed.

**Comment by eichelbe** [comment]
Configuration Tree: no changes due to caused problems / executed validation visible.

**Comment by eichelbe** [comment]
Testing now looks better:
- Configuration tree making does not disappear after fix and re-validation (in my case - first machine same name as second)
- Pipeline marking does not disappear after fix and re-validation (in my case, flow from financial to sentiment preprocessor)

**Comment by eichelbe** [comment]
Configuration tree looks fine, Niko is going on with getting rid of the markings of the variable/pipeline editor.

**Comment by eichelbe** [comment]
Variable editor working now after closing #2
