### ISSUE TITLE
Writing a configuration seems to include also derived values

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#33]
EASy-Producer: Writing a configuration with compound values (constraint variables, DML in QualiMaster) seems to include also derived variables. This might be caused by wrong states assigned by the reasoner or by not considering the states of nested variables while writing in the ConfigurationSaver.

If fixed, please x-check the QM model as some of the constraint variables seem to be written as "var = true", which is typically not intended.

**Comment by Elscha** [comment]
Fixed with commit SSEHUB/EASyProducer@40f97b126594eef64b9a887272ee6ae6e117f6ca
