### ISSUE TITLE
UI editor for new data source/sink does not scale to full window

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#34]
When creating a new data source/sink at least on my machine the contained editors do not scale to the full container size.

**Comment by Nowatzki** [comment]
Made it look a lot nicer. But still the size is limited to a fixed value.

**Comment by eichelbe** [comment]
Please check with different resolutions, Windows/Linux. If the actual approach survives, it's ok. If not, we need to dig into the layout structure of the editors.

**Comment by Nowatzki** [comment]
Updated the layout of editors. I am not sure wether you want this(now again implemented solution) due to the fact that I already did something like this in the past and we changed it back to a fixed size. Let me know if something is not okay.

**Comment by eichelbe** [comment]
To be checked again
