### ISSUE TITLE
Reasoner does not seem to detect mismatched family in pipeline

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#35]
Please check / validate. In case that the unmatched family does not fit anymore to the recent constraints, please update the unmatched family so that it again leads to a validation error and please include the unmatched family into the QM-IConf test scenarios.

**Comment by eichelbe** [comment]
Cui: related to #14, potentially only if family is connected to source

**Comment by eichelbe** [comment]
working now on Sascha's machine...

**Comment by eichelbe** [comment]
... but not if you change the preprocessor into the mismatched family!

**Comment by Elscha** [comment]
![not detected missmatch](https://cloud.githubusercontent.com/assets/6489033/12475055/614fe0a6-c020-11e5-9497-e8ad12916680.png)

**Comment by eichelbe** [comment]
Detected with new version of model. Turned into test case.
