### ISSUE TITLE
Illegal pipleline structure leads to exception in pipeline editor.

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#37]
If a pipeline is created inside the pipeline editor which is not supported by the underlying IVML model (compound types), the editor is displaying an exception when the user tries to save it.
Illegal structures should detected as early as possible and the user should be informed with an understandable message Instead of displaying the exception.
For instance (DataManagementElement -> Source):
![illegal structure](https://cloud.githubusercontent.com/assets/6489033/12177863/afc04a94-b56e-11e5-9b1e-7234ed0124db.png)
Displayed dialog (after trying to save it)
![dialog](https://cloud.githubusercontent.com/assets/6489033/12177893/df0bac1c-b56e-11e5-8e97-bc1d8c5e762c.png)
/cc @eichelbe

**Comment by eichelbe** [comment]
from #36: Structurally invalid pipelines, such as connecting a family back to a source are explicitly not supported by the IVML model. If such a pipeline shall be written anyway, it seems that just an exception is thrown and it remains unclear what happens to the model. This shall result in a specific exception caught in the UI leading to a message that this pipeline cannot be stored as it is structurally invalid (including reason(s)) and the model shall not be changed.

**Comment by eichelbe** [comment]
Thanks for the figures ;)
