### ISSUE TITLE
Input/output constraint does not point out the mismatched case while connecting to the DataManagement Element

### ISSUE THREAD

**Issue by cuiqin** [QualiMaster/QM-IConf#38]
If an DataManagement element is connected between two mismatched elements (source/family/sink), the input/output constraint does not catch the mismatch problem.

**Comment by cuiqin** [comment]
Test scenario:
  In the pipeline testDMPip, change the sink to the mismatched one "Priority Data Sink" and validate it. 
  
Result: validation is ok!
Expected result: validation has problem.

See the figure:
<img width="950" alt="issue38" src="https://cloud.githubusercontent.com/assets/12545053/12235997/a899c09a-b877-11e5-85e9-a870ff0a23b9.PNG">

**Comment by eichelbe** [comment]
DME did assign but not propagate inputTypes<->outputTypes.
