### ISSUE TITLE
Changing configuration settings a second time

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#42]
... causes invalid display on the UI

**Comment by eichelbe** [comment]
Also happens when deleting and re-adding an element directly in sequence.

**Comment by eichelbe** [comment]
Tried it on my machine, with/without deleting. Does not occur. Could you please re-check and report the exact sequence of steps. Thans.

**Comment by Elscha** [comment]
Partially fixed with SSEHUB/EASyProducer@c28596e9bd1a12e0971eaffff053054fbe434b9f

**Comment by eichelbe** [comment]
Occured while testing nested display of machines in groups. Seems to be caused by a subsequent change event of the ports. Shall now be filtered out -> 9af371195d54cc6531f53012f11287c604bd116c
