### ISSUE TITLE
Check layout for constraint cell editor for pipeline editor 

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#43]
Seems to accept "name > 1"

**Comment by eichelbe** [comment]
Seems to be not visible in the Linux version - editor button layout problem.

**Comment by eichelbe** [comment]
4fa4a2f60f9e806bc9a995e1dec46a5e0991067d: constraint check added to constraint editor dialog

**Comment by eichelbe** [comment]
Changing topic to cell editor layout problem - not nice in windows, seems to be not there in Linux

**Comment by Elscha** [comment]
Closed by https://github.com/QualiMaster/QM-IConf/commit/4e81f590d0dbb50747db97a619a60823cbce6bdc (Wrong number in commit message :-S)
