### ISSUE TITLE
ArtifactEditor close button not shown in Linux version

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#44]

**Comment by eichelbe** [comment]
Refresh brings me to the root of the tree and closes all member. Thus, I'm lost and I do not know how to navigate back to the qualimaster artifacts.

**Comment by sassai** [comment]
Unfortunately did the last commit not fix the issue for a custom font size bigger than 125%.

**Comment by sassai** [comment]
Fixed.
