### ISSUE TITLE
Reasoning error decorator does not appear under Linux

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#45]
role is not decorated, everything else is decorated correctly

**Comment by Elscha** [comment]
'Display.getCurrent().getActiveShell()' seems not to work under Linux as expected after working with Windows. It returns null, which forces the decoration algorithm (and also some other parts) to crash. Please be try to avoid calling 'Display.getCurrent().getActiveShell()', use 'getParent().getshell()' or for Dialogs 'new Shell()' instead.

**Comment by eichelbe** [comment]
Hi,

oha. Können wir da vielleicht irgendwie mal ne Seite zusammenschreiben
wo das Zeugs drinsteht. Aike hatte ja auch sowas wie kein Progress-Bar
während Dialog-Init. Startpunkt könnte ne Wiki-Seite im Projekt oder bei
uns sein.. oder ein SSE-Eclipse-Blog ;)

Was denkst Du?

Holger

On 26.02.2016 08:15, Sascha El-Sharkawy wrote:
> 'Display.getCurrent().getActiveShell()' seems not to work under Linux as
> expected after working with Windows. It returns null, which forces the
> decoration algorithm (and also some other parts) to crash. Please be try
> to avoid calling 'Display.getCurrent().getActiveShell()', use
> 'getParent().getshell()' or for Dialogs 'new Shell()' instead.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QualiMaster/QM-IConf/issues/45#issuecomment-189143403>.
> 


-- 
------------------------------------------------------------------------
Dr. Holger Eichelberger
Software Systems Engineering
University of Hildesheim         Tel.: +49 (0) 5121 / 883-40334
Institute of Computer Science    Fax.: +49 (0) 5121 / 883-40331
Universitätsplatz 1              eichelberger@sse.uni-hildesheim.de
D-31141 Hildesheim, Germany

http://www.uni-hildesheim.de/de/eichelberger.htm

PGP public key:

https://www.uni-hildesheim.de/media/fb4/informatik/AG_SSE/pgp/sse_he_pubkey.asc
PGP fingerprint:
  4522 685C 57E5 D0EA D5BA  4EDE C53F 5B9D 9F71 55E7

------------------------------------------------------------------------

Adaptive Big Data Infrastructure for financial Risk Analysis (FP7)
http://qualimaster.eu

1st Intl Big Data Processing - Reloaded Workshop
http://bdpr2016.l3s.uni-hannover.de/

------------------------------------------------------------------------

**Comment by Elscha** [comment]
Hilfreich wäre es auf jeden Fall. Zumindest wenn die Studis es lesen (hatte früher schon mal ein Wiki dazu angelegt wo ich gängige Eclipse Probleme und Wege aufgelistet hatte, schien aber auch niemand zu lesen).
Die Frage ist nur wo. Da wir derzeit das Agilo nicht mehr nutzen, ist die Frage ob es auf kurz oder lang abgeschaltet werden soll (kann sein, dass der Projects neu aufgesetzt werden muss, das ist aber eine andere Geschichte).

Mit freundlichen Grüßen
Sascha El-Sharkawy

-- -----------------------------------------------------------------------
Sascha El-Sharkawy, MSc
University of Hildesheim                    Tel.: +49 (0) 5121 / 883-40336
Institute of Computer Science               Fax:  +49 (0) 5121 / 883-40337
Universitätsplatz 1                           elscha@sse.uni-hildesheim.de<mailto:elscha@sse.uni-hildesheim.de>
D-31141 Hildesheim, Germany               http://www.sse.uni-hildesheim.de<http://www.sse.uni-hildesheim.de/>

Von: Holger Eichelberger [mailto:notifications@github.com]
Gesendet: Freitag, 26. Februar 2016 08:19
An: QualiMaster/QM-IConf
Cc: Sascha El-Sharkawy
Betreff: Re: [QM-IConf] Reasoning error decorator does not appear under Linux (#45)

Hi,

oha. Können wir da vielleicht irgendwie mal ne Seite zusammenschreiben
wo das Zeugs drinsteht. Aike hatte ja auch sowas wie kein Progress-Bar
während Dialog-Init. Startpunkt könnte ne Wiki-Seite im Projekt oder bei
uns sein.. oder ein SSE-Eclipse-Blog ;)

Was denkst Du?

Holger

On 26.02.2016 08:15, Sascha El-Sharkawy wrote:
> 'Display.getCurrent().getActiveShell()' seems not to work under Linux as
> expected after working with Windows. It returns null, which forces the
> decoration algorithm (and also some other parts) to crash. Please be try
> to avoid calling 'Display.getCurrent().getActiveShell()', use
> 'getParent().getshell()' or for Dialogs 'new Shell()' instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QualiMaster/QM-IConf/issues/45#issuecomment-189143403>.
>


--
------------------------------------------------------------------------
Dr. Holger Eichelberger
Software Systems Engineering
University of Hildesheim Tel.: +49 (0) 5121 / 883-40334
Institute of Computer Science Fax.: +49 (0) 5121 / 883-40331
Universitätsplatz 1 eichelberger@sse.uni-hildesheim.de<mailto:eichelberger@sse.uni-hildesheim.de>
D-31141 Hildesheim, Germany

http://www.uni-hildesheim.de/de/eichelberger.htm

PGP public key:

https://www.uni-hildesheim.de/media/fb4/informatik/AG_SSE/pgp/sse_he_pubkey.asc
PGP fingerprint:
4522 685C 57E5 D0EA D5BA 4EDE C53F 5B9D 9F71 55E7

------------------------------------------------------------------------

Adaptive Big Data Infrastructure for financial Risk Analysis (FP7)
http://qualimaster.eu

1st Intl Big Data Processing - Reloaded Workshop
http://bdpr2016.l3s.uni-hannover.de/

------------------------------------------------------------------------

**Comment by eichelbe** [comment]
Ich dachte erst an

http://www.planeteclipse.org/planet/#blogs

Aber da scheint es kompliziert einen Blog zu bekommen (über Change
Tracker).

Blogspot via Google?

Mir schwebt das gerade im Kopf rum, da die Reviewer uns angeraten haben
zu bloggen um das Projekt irgendwie bekannter zu machen. Das wäre zwar
Eclipse-technisch, aber könnt dennoch einen Link auf QM hinterlassen.

Aber wir können auch erst mal einfach im Wiki sammeln damit die Info
nicht verschwindet.

Holger

On 26.02.2016 08:21, Sascha El-Sharkawy wrote:
> Hilfreich wäre es auf jeden Fall. Zumindest wenn die Studis es lesen
> (hatte früher schon mal ein Wiki dazu angelegt wo ich gängige Eclipse
> Probleme und Wege aufgelistet hatte, schien aber auch niemand zu lesen).
> Die Frage ist nur wo. Da wir derzeit das Agilo nicht mehr nutzen, ist
> die Frage ob es auf kurz oder lang abgeschaltet werden soll (kann sein,
> dass der Projects neu aufgesetzt werden muss, das ist aber eine andere
> Geschichte).
> 
> Mit freundlichen Grüßen
> Sascha El-Sharkawy
> 
> -- -----------------------------------------------------------------------
> Sascha El-Sharkawy, MSc
> University of Hildesheim Tel.: +49 (0) 5121 / 883-40336
> Institute of Computer Science Fax: +49 (0) 5121 / 883-40337
> Universitätsplatz 1
> elscha@sse.uni-hildesheim.de<mailto:elscha@sse.uni-hildesheim.de>
> D-31141 Hildesheim, Germany
> http://www.sse.uni-hildesheim.de<http://www.sse.uni-hildesheim.de/>
> 
> Von: Holger Eichelberger [mailto:notifications@github.com]
> Gesendet: Freitag, 26. Februar 2016 08:19
> An: QualiMaster/QM-IConf
> Cc: Sascha El-Sharkawy
> Betreff: Re: [QM-IConf] Reasoning error decorator does not appear under
> Linux (#45)
> 
> Hi,
> 
> oha. Können wir da vielleicht irgendwie mal ne Seite zusammenschreiben
> wo das Zeugs drinsteht. Aike hatte ja auch sowas wie kein Progress-Bar
> während Dialog-Init. Startpunkt könnte ne Wiki-Seite im Projekt oder bei
> uns sein.. oder ein SSE-Eclipse-Blog ;)
> 
> Was denkst Du?
> 
> Holger
> 
> On 26.02.2016 08:15, Sascha El-Sharkawy wrote:
>> 'Display.getCurrent().getActiveShell()' seems not to work under Linux as
>> expected after working with Windows. It returns null, which forces the
>> decoration algorithm (and also some other parts) to crash. Please be try
>> to avoid calling 'Display.getCurrent().getActiveShell()', use
>> 'getParent().getshell()' or for Dialogs 'new Shell()' instead.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
> <https://github.com/QualiMaster/QM-IConf/issues/45#issuecomment-189143403>.
>>
> 
> 
> -- 
> ------------------------------------------------------------------------
> Dr. Holger Eichelberger
> Software Systems Engineering
> University of Hildesheim Tel.: +49 (0) 5121 / 883-40334
> Institute of Computer Science Fax.: +49 (0) 5121 / 883-40331
> Universitätsplatz 1
> eichelberger@sse.uni-hildesheim.de<mailto:eichelberger@sse.uni-hildesheim.de>
> 
> D-31141 Hildesheim, Germany
> 
> http://www.uni-hildesheim.de/de/eichelberger.htm
> 
> PGP public key:
> 
> https://www.uni-hildesheim.de/media/fb4/informatik/AG_SSE/pgp/sse_he_pubkey.asc
> 
> PGP fingerprint:
> 4522 685C 57E5 D0EA D5BA 4EDE C53F 5B9D 9F71 55E7
> 
> ------------------------------------------------------------------------
> 
> Adaptive Big Data Infrastructure for financial Risk Analysis (FP7)
> http://qualimaster.eu
> 
> 1st Intl Big Data Processing - Reloaded Workshop
> http://bdpr2016.l3s.uni-hannover.de/
> 
> ------------------------------------------------------------------------
> 
> 
> 
> —
> Reply to this email directly or view it on
> GitHub<https://github.com/QualiMaster/QM-IConf/issues/45#issuecomment-189143894>.
> 
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QualiMaster/QM-IConf/issues/45#issuecomment-189144193>.
> 


-- 
------------------------------------------------------------------------
Dr. Holger Eichelberger
Software Systems Engineering
University of Hildesheim         Tel.: +49 (0) 5121 / 883-40334
Institute of Computer Science    Fax.: +49 (0) 5121 / 883-40331
Universitätsplatz 1              eichelberger@sse.uni-hildesheim.de
D-31141 Hildesheim, Germany

http://www.uni-hildesheim.de/de/eichelberger.htm

PGP public key:

https://www.uni-hildesheim.de/media/fb4/informatik/AG_SSE/pgp/sse_he_pubkey.asc
PGP fingerprint:
  4522 685C 57E5 D0EA D5BA  4EDE C53F 5B9D 9F71 55E7

------------------------------------------------------------------------

Adaptive Big Data Infrastructure for financial Risk Analysis (FP7)
http://qualimaster.eu

1st Intl Big Data Processing - Reloaded Workshop
http://bdpr2016.l3s.uni-hannover.de/

------------------------------------------------------------------------
