### ISSUE TITLE
Linux: Pipelines are not generated

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#47]
Apostolos used the "Instantiate Pipeline", but there was no generated code.

**Comment by eichelbe** [comment]
Might be asking Nikos/Apostolos again would help. It seems that it is working now...

**Comment by eichelbe** [comment]
Sascha: pipelines are created but not model-gen (on Linux)

**Comment by Elscha** [comment]
There was a bug inside the QM_0.vil script. Cui fixed that today. With that fix I was able to generate the pipelines under Linux (Ubuntu 14.04, x64).
Test protocol: [Plattform Instantiation.xlsx](https://github.com/QualiMaster/QM-IConf/files/124836/Plattform.Instantiation.xlsx)
