### ISSUE TITLE
Provide initial empty model

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#5]
Please commit as model.zip and test whether the tool takes it up correctly.

**Comment by Elscha** [comment]
Model.zip will be created and published to: http://jenkins.sse.uni-hildesheim.de/job/QM-Pipelines/lastSuccessfulBuild/artifact/build/model/QM_Model.zip
Needs to be tested.

**Comment by eichelbe** [comment]
Thanks. Aike can take this up as part of #1 and then commit the most recent version.
