### ISSUE TITLE
Tool is not restarting after the model is updated from the repository

### ISSUE THREAD

**Issue by rsizonenko** [QualiMaster/QM-IConf#50]
After updating the model from the tools UI (Model -> Update from Repository) tool needs to restart automatically, so he updated model is loaded and changes become visible in the UI.

**Comment by sassai** [comment]
The tool will no restart after an update was performed. For better usability it would be nice if the tool doesn't need the restart after all. Following steps have to be implemented for this to work in the future: 
- Close editors
- Remove the locations from the VarModel (?)
- Clear the usability model cache
- Add the location to the VarModel
- recreate the ConfElement tree (?)

Steps marked with a question mark are not implemented yet.

@rsizonenko can you test the restart of the tool when there are changes in the repository?

**Comment by rsizonenko** [comment]
@sassai  Tested the fix. Now the tool restarts and changes are visible.
