### ISSUE TITLE
Explicit deployment of pipelines

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#6]
Requires target Maven Repository in the Configuration (for QM on Nexus)
Check for generated pipeline artifact
Submit via Ivy
Bind to Pipeline context menu and administrative user

**Comment by eichelbe** [comment]
Deployment URL is in the model.

**Comment by sassai** [comment]
Credentials are stored in RepositoryConnector.UserContext.

**Comment by eichelbe** [comment]
check ManifestConnection#publish
  - ivy.deliver against C:/ vs. Linux vs. mavenPath
  - setRoot fixed against already existing configuration methods

**Comment by eichelbe** [comment]
Just that I do not forget... I think that a single deploy button would be better, as the deployment would be then consistent, e.g., as Menu entry in instantiate. Therefore the Model Artifact, the Interface artifact as well as the artifacts of the active pipelines (see InfrastructureCfg) shall be deployed in one step and the individual context menu entries can be removed.

**Comment by eichelbe** [comment]
Did this proceed somehow?

**Comment by Pastuschek** [comment]
Is implemented, but ivy fails to convert the pom to its ivy representation, due to dependency issues. This might however be related to a maven error when instantiating (that at least I recieve): "Maven build failed calling maven build(Path)"

**Comment by eichelbe** [comment]
The message seems to indicate either a VIL/VTL problem or a compile problem - or a recent problem due to the power outage. Could you please detail the problem so that we can cross-check with @cuiqin

**Comment by eichelbe** [comment]
Any news regarding the dependency issues?

**Comment by Pastuschek** [comment]
Ivy has been removed and deployment is functional. Implementation now works with org.apache.commons.net.ftp, which also allows for more control during the upload process.
