### ISSUE TITLE
Checking the tuple name in the input-output constraint is missing

### ISSUE THREAD

**Issue by cuiqin** [QualiMaster/QM-IConf#60]
Currently the input-output check constraint for pipeline elements checked only the field name and field type. Checking on the tuple name is missing.

**Comment by eichelbe** [comment]
Indeed, but how urgent is this?

**Comment by cuiqin** [comment]
So far I can see, others' configuration fails there. They may accidentally delete the tuple item by selecting 'delete the selected field'. Then the configuration remains inconsistent but the validation does not detect.

**Comment by cuiqin** [comment]
Ohh, the tuple deletion bug is solved.. Then potentially this case can be protected...

**Comment by eichelbe** [comment]
Anyway, we shall take this into account. I have a simple potential solution, which requires some "discussion" with EASy/IVML...

**Comment by eichelbe** [comment]
Done on QM2.devel in Families, just adding the tuple name to the field names. Detected the first inconsistency, fixed by Cui, finally no validation problem ;)
