### ISSUE TITLE
Add description field to provided in Manifests

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#62]
Optional description field for Manifests in provided, to be taken over into the algorithms, sources and sinks.

**Comment by Pastuschek** [comment]
Does any artifact already have a description (for testing purposes)?
Is implemented (not marked as closed as long as no proper testing is occured).

**Comment by eichelbe** [comment]
No, as we did not have the XML syntax for that by now. But we can easily modify an artifact for that purpose.

**Comment by eichelbe** [comment]
@cuiqin Added a test description to the financial preprocessor (Priority Pipeline). Did not see an algorithm with parameters to add a default value.

**Comment by cuiqin** [comment]
@eichelbe You can use the software financial correlation algorithm which has parameters and the manifest file.

**Comment by eichelbe** [comment]
Thanks. Added a parameter to the manifest of the software HY correlation. Please test both and confirm here.

**Comment by eichelbe** [comment]
Any news about testing the parameter???

**Comment by Pastuschek** [comment]
Description is read correctly (if available).
