### ISSUE TITLE
Manifest analysis: implementation class/topology missing in editor

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#67]
Configuring a new algorithm, in case of a topology the entry for the class seems to be disappearing and there is no entry for the Topology.

Please clarify with @cuiqin what exactly must be in the topology entry (qualified or simple class name) and how this relates to the class entry.

**Comment by eichelbe** [comment]
added @rsizonenko due to the scenario / video creation

**Comment by cuiqin** [comment]
In the algorithm configuration, the "class" is the full qualified name and the "algTopologyClass" is only the simple class name. For example, for the software correlation algorithm, the "class" is configured to "eu.qualimaster.algorithms.imp.correlation.softwaresubtopology.TopoSoftwareCorrelationFinancial" while the "algTopologyClass" is configured to the implementing class name, i.e., "TopoSoftwareCorrelationFinancial".

**Comment by eichelbe** [comment]
I.e., we can infer the topology class name from the qualified class name of the Manifest.

@cuiqin In the model the topology name is just a String rather than a class name. If so, we shall schedule an issue to change the model accordingly, because currently QM-IConf is showing a class selection button there :o Is this right?

**Comment by cuiqin** [comment]
yes, in the model the topology name is just a String.

**Comment by eichelbe** [comment]
Ok, created an issue for that (#68) and marked it as not so urgent ;)

**Comment by eichelbe** [comment]
Working on this.

**Comment by eichelbe** [comment]
@Elscha Could you please have a look why the topoAlgorithmClass field is not updated in the UI. Tested against eu/qualimaster:hy-correlation-financial-software:3.2-SNAPSHOT in a new Algorithm instance.

**Comment by Elscha** [comment]
Also referenced by https://github.com/SSEHUB/EASyProducer/commit/183ea111bb2f2a73979a88ac41cca5df385555d6

**Comment by eichelbe** [comment]
Working
