### ISSUE TITLE
Manifest analysis: Refactor code

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#72]
ManifestConnection rebuilds class loader and performs manifest reading again and again.

If there is no serious issue against the following, please refactor towards:
- open connection
  - build classloader
  - read manifest
  - return manifest
  - provide access to classes
  - close connection (caller shall do this as soon as possible)
- pass manifest as result and use operations / data from manifest rather than from connection

Other suggestions are welcome.

**Comment by eichelbe** [comment]
is this done?

**Comment by eichelbe** [comment]
just added sascha the "old" way...

**Comment by Elscha** [comment]
Why? Already 2nd time assigned
![double assignment](https://cloud.githubusercontent.com/assets/6489033/15669098/d367bdac-271e-11e6-8951-380f0af4c27b.png)

**Comment by eichelbe** [comment]
Happened along with requesting information about the pending other tasks. Any news until now except for the double assignment?

**Comment by Elscha** [comment]
Since yesterday no new information. I wrote Partrik a mail...

**Comment by Pastuschek** [comment]
Is fixed, the actual (time consuming) ivy connection will only be used once per analysis.
