### ISSUE TITLE
Maven Artifact selector

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#76]
Result can end up with :: instead of maven spec if clicking an inner tree node instead of a version leaf. Avoid that user can do that.

**Comment by eichelbe** [comment]
@sassai JFYI

**Comment by Elscha** [comment]
Referenced by
https://github.com/QualiMaster/QM-IConf/commit/500e2f41143459149730deae7cf67ca6991af91e
https://github.com/QualiMaster/QM-IConf/commit/99c18223ffaf0ec301f9d24263cacaeb1174f50d

It still keeps unclear whether the current input should be clearted if the user clicks on a folder. Currently, the old selection (las artifact) will be kept.

**Comment by eichelbe** [comment]
I think that clearing the input by clicking on an inner node shall not happen at all. A too sensitive UI might confuse the user.

**Comment by Elscha** [comment]
Current Dialog needs a GroupID, an ArtifactID and a version, otherweise a error message will be shown while trying to close the editor.
