### ISSUE TITLE
Manifest analysis: increase tolerance of parser

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#77]
Consider input of incomplete / invalid manifests, in particular missing XML attributes potentially leading to NPEs crashing QM-IConf. In that case, create an error message (using the Dialogs class) so that the user is informed properly.

**Comment by eichelbe** [comment]
Is this done?

**Comment by Pastuschek** [comment]
Yes, minor issues will be ignored, while major issues will be reported via the UI (and console).
