### ISSUE TITLE
Refactor runtime connection

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#8]
Provide a global connection into the infrastructure. Move runtime connection information from "Runtime" editor into Menu entries. Store last connection information in .metadata. Refactor "Runtime" editor so that it works with the global runtime connection

**Comment by Nowatzki** [comment]
Added class ConnectDialog. For now it is just asking for an ip, port and creates a connection. If connection is opened, the data is stored in .metadata. RuntimeEditor is not adjusted.
