### ISSUE TITLE
Connect button does not show in the popup window of the Infrastructure connection 

### ISSUE THREAD

**Issue by cuiqin** [QualiMaster/QM-IConf#87]
It seems the infrastructure connection window uses a fixed size and the connect button doesn't show on my machine. 
![image](https://cloud.githubusercontent.com/assets/12545053/13664067/69cfb552-e6a5-11e5-9d15-865c38199fea.png)

**Comment by eichelbe** [comment]
Seems to be again a layout problem, probably due to screen resolution. @sassai / @Nowatzki can you please take this over.
