### ISSUE TITLE
RepositoryConnector: Not Possible to Switch Back to Online Mode After Staying in Local Mode

### ISSUE THREAD

**Issue by Elscha** [QualiMaster/QM-IConf#90]
Scenario:

1. Start QM-IConf in local mode (check the checkbox during start up), make any changes to the model, and save
1. Start QM-Iconf in online mode (login with valid credentials)
1. If the tool asks you, whether you want to keep changes or want to switch into online mode, answer the dialog with "Yes" to stay in local mode
1. Restart QM-IConf, the tool will no longer ask you to switch into online mode to update the model (this can only be done via the revert/update function in the menu after the tool is running).

Suggestion: Al least if the user enters a user name (and unchecks the checkbox), the tool should ask whether it should switch into online mode. This should be done automatically if it does not find any changes (currently the case).

@eichelbe

**Comment by sassai** [comment]
@eichelbe @Elscha 

The tool now reminds the user very time if he worked on local data in the previous session.

Problem remaining: If the user authenticates successfully he is able to update the model or commit changes even though he is still working on local data. This can lead to conflicts in the working space. How should we handle this? 

Right now the application will overwrite all local changes when conflicts occur while committing/updating.

**Comment by eichelbe** [comment]
What about asking the user the same way as during login?

**Comment by sassai** [comment]
This issue was fixed with the hotfix on Mar 24.
