### ISSUE TITLE
ManifestUtils: Use code annotation for defining a parameter default value

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/QM-IConf#98]
To define the default value, currently the full specification of the parameter is needed in the Manifest, while other information is taken over from code. The reason is that the actual default value cannot be detected (without more complex analysis) from code. To simplify manifest definition, please consider while code analysis the presence of the @DefaultValue annotation (eu.qualimaster.base.algorithm.DefaultValue) and take the value given there over into the parsed manifest information.

**Comment by eichelbe** [comment]
... please update finally the Manifest description in the Wiki...

**Comment by eichelbe** [comment]
Any news here?

**Comment by Pastuschek** [comment]
Has been implemented.
I still don't have access to the wiki... (wiki was updated via Elscha)
